services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Reserva
    ports:
      - "5432:5432"  # Mapeia a porta do contêiner para a porta do host
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_node_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    # volumes:
    #   - ../src:/usr/src/app/src
    command: node app.js
volumes:
  pgdata: