services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Mapeia a porta do contêiner para a porta do host
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_node_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/mydatabase
    volumes:
      - ../src:/usr/src/app/src
    command: node src/app.js
volumes:
  pgdata: